"""Static Unicode emoji category mapping used by the emoji picker.

Generated from Unicode 15.1 ``emoji-test.txt`` group headers. Emoji variants
containing skin-tone, hair-style, or gender components are intentionally omitted
because the picker presents the default/base glyph for each concept.
"""

EMOJI_CATEGORIES: dict[str, str] = {
    '😀': 'Smileys & Emotion',
    '😃': 'Smileys & Emotion',
    '😄': 'Smileys & Emotion',
    '😁': 'Smileys & Emotion',
    '😆': 'Smileys & Emotion',
    '😅': 'Smileys & Emotion',
    '🤣': 'Smileys & Emotion',
    '😂': 'Smileys & Emotion',
    '🙂': 'Smileys & Emotion',
    '🙃': 'Smileys & Emotion',
    '🫠': 'Smileys & Emotion',
    '😉': 'Smileys & Emotion',
    '😊': 'Smileys & Emotion',
    '😇': 'Smileys & Emotion',
    '🥰': 'Smileys & Emotion',
    '😍': 'Smileys & Emotion',
    '🤩': 'Smileys & Emotion',
    '😘': 'Smileys & Emotion',
    '😗': 'Smileys & Emotion',
    '☺️': 'Smileys & Emotion',
    '😚': 'Smileys & Emotion',
    '😙': 'Smileys & Emotion',
    '🥲': 'Smileys & Emotion',
    '😋': 'Smileys & Emotion',
    '😛': 'Smileys & Emotion',
    '😜': 'Smileys & Emotion',
    '🤪': 'Smileys & Emotion',
    '😝': 'Smileys & Emotion',
    '🤑': 'Smileys & Emotion',
    '🤗': 'Smileys & Emotion',
    '🤭': 'Smileys & Emotion',
    '🫢': 'Smileys & Emotion',
    '🫣': 'Smileys & Emotion',
    '🤫': 'Smileys & Emotion',
    '🤔': 'Smileys & Emotion',
    '🫡': 'Smileys & Emotion',
    '🤐': 'Smileys & Emotion',
    '🤨': 'Smileys & Emotion',
    '😐': 'Smileys & Emotion',
    '😑': 'Smileys & Emotion',
    '😶': 'Smileys & Emotion',
    '🫥': 'Smileys & Emotion',
    '😶\u200d🌫️': 'Smileys & Emotion',
    '😏': 'Smileys & Emotion',
    '😒': 'Smileys & Emotion',
    '🙄': 'Smileys & Emotion',
    '😬': 'Smileys & Emotion',
    '😮\u200d💨': 'Smileys & Emotion',
    '🤥': 'Smileys & Emotion',
    '🫨': 'Smileys & Emotion',
    '🙂\u200d↔️': 'Smileys & Emotion',
    '🙂\u200d↕️': 'Smileys & Emotion',
    '😌': 'Smileys & Emotion',
    '😔': 'Smileys & Emotion',
    '😪': 'Smileys & Emotion',
    '🤤': 'Smileys & Emotion',
    '😴': 'Smileys & Emotion',
    '😷': 'Smileys & Emotion',
    '🤒': 'Smileys & Emotion',
    '🤕': 'Smileys & Emotion',
    '🤢': 'Smileys & Emotion',
    '🤮': 'Smileys & Emotion',
    '🤧': 'Smileys & Emotion',
    '🥵': 'Smileys & Emotion',
    '🥶': 'Smileys & Emotion',
    '🥴': 'Smileys & Emotion',
    '😵': 'Smileys & Emotion',
    '😵\u200d💫': 'Smileys & Emotion',
    '🤯': 'Smileys & Emotion',
    '🤠': 'Smileys & Emotion',
    '🥳': 'Smileys & Emotion',
    '🥸': 'Smileys & Emotion',
    '😎': 'Smileys & Emotion',
    '🤓': 'Smileys & Emotion',
    '🧐': 'Smileys & Emotion',
    '😕': 'Smileys & Emotion',
    '🫤': 'Smileys & Emotion',
    '😟': 'Smileys & Emotion',
    '🙁': 'Smileys & Emotion',
    '☹️': 'Smileys & Emotion',
    '😮': 'Smileys & Emotion',
    '😯': 'Smileys & Emotion',
    '😲': 'Smileys & Emotion',
    '😳': 'Smileys & Emotion',
    '🥺': 'Smileys & Emotion',
    '🥹': 'Smileys & Emotion',
    '😦': 'Smileys & Emotion',
    '😧': 'Smileys & Emotion',
    '😨': 'Smileys & Emotion',
    '😰': 'Smileys & Emotion',
    '😥': 'Smileys & Emotion',
    '😢': 'Smileys & Emotion',
    '😭': 'Smileys & Emotion',
    '😱': 'Smileys & Emotion',
    '😖': 'Smileys & Emotion',
    '😣': 'Smileys & Emotion',
    '😞': 'Smileys & Emotion',
    '😓': 'Smileys & Emotion',
    '😩': 'Smileys & Emotion',
    '😫': 'Smileys & Emotion',
    '🥱': 'Smileys & Emotion',
    '😤': 'Smileys & Emotion',
    '😡': 'Smileys & Emotion',
    '😠': 'Smileys & Emotion',
    '🤬': 'Smileys & Emotion',
    '😈': 'Smileys & Emotion',
    '👿': 'Smileys & Emotion',
    '💀': 'Smileys & Emotion',
    '☠️': 'Smileys & Emotion',
    '💩': 'Smileys & Emotion',
    '🤡': 'Smileys & Emotion',
    '👹': 'Smileys & Emotion',
    '👺': 'Smileys & Emotion',
    '👻': 'Smileys & Emotion',
    '👽': 'Smileys & Emotion',
    '👾': 'Smileys & Emotion',
    '🤖': 'Smileys & Emotion',
    '😺': 'Smileys & Emotion',
    '😸': 'Smileys & Emotion',
    '😹': 'Smileys & Emotion',
    '😻': 'Smileys & Emotion',
    '😼': 'Smileys & Emotion',
    '😽': 'Smileys & Emotion',
    '🙀': 'Smileys & Emotion',
    '😿': 'Smileys & Emotion',
    '😾': 'Smileys & Emotion',
    '🙈': 'Smileys & Emotion',
    '🙉': 'Smileys & Emotion',
    '🙊': 'Smileys & Emotion',
    '💌': 'Smileys & Emotion',
    '💘': 'Smileys & Emotion',
    '💝': 'Smileys & Emotion',
    '💖': 'Smileys & Emotion',
    '💗': 'Smileys & Emotion',
    '💓': 'Smileys & Emotion',
    '💞': 'Smileys & Emotion',
    '💕': 'Smileys & Emotion',
    '💟': 'Smileys & Emotion',
    '❣️': 'Smileys & Emotion',
    '💔': 'Smileys & Emotion',
    '❤️\u200d🔥': 'Smileys & Emotion',
    '❤️\u200d🩹': 'Smileys & Emotion',
    '❤️': 'Smileys & Emotion',
    '🩷': 'Smileys & Emotion',
    '🧡': 'Smileys & Emotion',
    '💛': 'Smileys & Emotion',
    '💚': 'Smileys & Emotion',
    '💙': 'Smileys & Emotion',
    '🩵': 'Smileys & Emotion',
    '💜': 'Smileys & Emotion',
    '🤎': 'Smileys & Emotion',
    '🖤': 'Smileys & Emotion',
    '🩶': 'Smileys & Emotion',
    '🤍': 'Smileys & Emotion',
    '💋': 'Smileys & Emotion',
    '💯': 'Smileys & Emotion',
    '💢': 'Smileys & Emotion',
    '💥': 'Smileys & Emotion',
    '💫': 'Smileys & Emotion',
    '💦': 'Smileys & Emotion',
    '💨': 'Smileys & Emotion',
    '🕳️': 'Smileys & Emotion',
    '💬': 'Smileys & Emotion',
    '👁️\u200d🗨️': 'Smileys & Emotion',
    '🗨️': 'Smileys & Emotion',
    '🗯️': 'Smileys & Emotion',
    '💭': 'Smileys & Emotion',
    '💤': 'Smileys & Emotion',
    '👋': 'People & Body',
    '🤚': 'People & Body',
    '🖐️': 'People & Body',
    '✋': 'People & Body',
    '🖖': 'People & Body',
    '🫱': 'People & Body',
    '🫲': 'People & Body',
    '🫳': 'People & Body',
    '🫴': 'People & Body',
    '🫷': 'People & Body',
    '🫸': 'People & Body',
    '👌': 'People & Body',
    '🤌': 'People & Body',
    '🤏': 'People & Body',
    '✌️': 'People & Body',
    '🤞': 'People & Body',
    '🫰': 'People & Body',
    '🤟': 'People & Body',
    '🤘': 'People & Body',
    '🤙': 'People & Body',
    '👈': 'People & Body',
    '👉': 'People & Body',
    '👆': 'People & Body',
    '🖕': 'People & Body',
    '👇': 'People & Body',
    '☝️': 'People & Body',
    '🫵': 'People & Body',
    '👍': 'People & Body',
    '👎': 'People & Body',
    '✊': 'People & Body',
    '👊': 'People & Body',
    '🤛': 'People & Body',
    '🤜': 'People & Body',
    '👏': 'People & Body',
    '🙌': 'People & Body',
    '🫶': 'People & Body',
    '👐': 'People & Body',
    '🤲': 'People & Body',
    '🤝': 'People & Body',
    '🙏': 'People & Body',
    '✍️': 'People & Body',
    '💅': 'People & Body',
    '🤳': 'People & Body',
    '💪': 'People & Body',
    '🦾': 'People & Body',
    '🦿': 'People & Body',
    '🦵': 'People & Body',
    '🦶': 'People & Body',
    '👂': 'People & Body',
    '🦻': 'People & Body',
    '👃': 'People & Body',
    '🧠': 'People & Body',
    '🫀': 'People & Body',
    '🫁': 'People & Body',
    '🦷': 'People & Body',
    '🦴': 'People & Body',
    '👀': 'People & Body',
    '👁️': 'People & Body',
    '👅': 'People & Body',
    '👄': 'People & Body',
    '🫦': 'People & Body',
    '👶': 'People & Body',
    '🧒': 'People & Body',
    '👦': 'People & Body',
    '👧': 'People & Body',
    '🧑': 'People & Body',
    '👱': 'People & Body',
    '👨': 'People & Body',
    '🧔': 'People & Body',
    '👩': 'People & Body',
    '🧓': 'People & Body',
    '👴': 'People & Body',
    '👵': 'People & Body',
    '🙍': 'People & Body',
    '🙎': 'People & Body',
    '🙅': 'People & Body',
    '🙆': 'People & Body',
    '💁': 'People & Body',
    '🙋': 'People & Body',
    '🧏': 'People & Body',
    '🙇': 'People & Body',
    '🤦': 'People & Body',
    '🤷': 'People & Body',
    '🧑\u200d⚕️': 'People & Body',
    '👨\u200d⚕️': 'People & Body',
    '👩\u200d⚕️': 'People & Body',
    '🧑\u200d🎓': 'People & Body',
    '👨\u200d🎓': 'People & Body',
    '👩\u200d🎓': 'People & Body',
    '🧑\u200d🏫': 'People & Body',
    '👨\u200d🏫': 'People & Body',
    '👩\u200d🏫': 'People & Body',
    '🧑\u200d⚖️': 'People & Body',
    '👨\u200d⚖️': 'People & Body',
    '👩\u200d⚖️': 'People & Body',
    '🧑\u200d🌾': 'People & Body',
    '👨\u200d🌾': 'People & Body',
    '👩\u200d🌾': 'People & Body',
    '🧑\u200d🍳': 'People & Body',
    '👨\u200d🍳': 'People & Body',
    '👩\u200d🍳': 'People & Body',
    '🧑\u200d🔧': 'People & Body',
    '👨\u200d🔧': 'People & Body',
    '👩\u200d🔧': 'People & Body',
    '🧑\u200d🏭': 'People & Body',
    '👨\u200d🏭': 'People & Body',
    '👩\u200d🏭': 'People & Body',
    '🧑\u200d💼': 'People & Body',
    '👨\u200d💼': 'People & Body',
    '👩\u200d💼': 'People & Body',
    '🧑\u200d🔬': 'People & Body',
    '👨\u200d🔬': 'People & Body',
    '👩\u200d🔬': 'People & Body',
    '🧑\u200d💻': 'People & Body',
    '👨\u200d💻': 'People & Body',
    '👩\u200d💻': 'People & Body',
    '🧑\u200d🎤': 'People & Body',
    '👨\u200d🎤': 'People & Body',
    '👩\u200d🎤': 'People & Body',
    '🧑\u200d🎨': 'People & Body',
    '👨\u200d🎨': 'People & Body',
    '👩\u200d🎨': 'People & Body',
    '🧑\u200d✈️': 'People & Body',
    '👨\u200d✈️': 'People & Body',
    '👩\u200d✈️': 'People & Body',
    '🧑\u200d🚀': 'People & Body',
    '👨\u200d🚀': 'People & Body',
    '👩\u200d🚀': 'People & Body',
    '🧑\u200d🚒': 'People & Body',
    '👨\u200d🚒': 'People & Body',
    '👩\u200d🚒': 'People & Body',
    '👮': 'People & Body',
    '🕵️': 'People & Body',
    '💂': 'People & Body',
    '🥷': 'People & Body',
    '👷': 'People & Body',
    '🫅': 'People & Body',
    '🤴': 'People & Body',
    '👸': 'People & Body',
    '👳': 'People & Body',
    '👲': 'People & Body',
    '🧕': 'People & Body',
    '🤵': 'People & Body',
    '👰': 'People & Body',
    '🤰': 'People & Body',
    '🫃': 'People & Body',
    '🫄': 'People & Body',
    '🤱': 'People & Body',
    '👩\u200d🍼': 'People & Body',
    '👨\u200d🍼': 'People & Body',
    '🧑\u200d🍼': 'People & Body',
    '👼': 'People & Body',
    '🎅': 'People & Body',
    '🤶': 'People & Body',
    '🧑\u200d🎄': 'People & Body',
    '🦸': 'People & Body',
    '🦹': 'People & Body',
    '🧙': 'People & Body',
    '🧚': 'People & Body',
    '🧛': 'People & Body',
    '🧜': 'People & Body',
    '🧝': 'People & Body',
    '🧞': 'People & Body',
    '🧟': 'People & Body',
    '🧌': 'People & Body',
    '💆': 'People & Body',
    '💇': 'People & Body',
    '🚶': 'People & Body',
    '🚶\u200d➡️': 'People & Body',
    '🧍': 'People & Body',
    '🧎': 'People & Body',
    '🧎\u200d➡️': 'People & Body',
    '🧑\u200d🦯': 'People & Body',
    '🧑\u200d🦯\u200d➡️': 'People & Body',
    '👨\u200d🦯': 'People & Body',
    '👨\u200d🦯\u200d➡️': 'People & Body',
    '👩\u200d🦯': 'People & Body',
    '👩\u200d🦯\u200d➡️': 'People & Body',
    '🧑\u200d🦼': 'People & Body',
    '🧑\u200d🦼\u200d➡️': 'People & Body',
    '👨\u200d🦼': 'People & Body',
    '👨\u200d🦼\u200d➡️': 'People & Body',
    '👩\u200d🦼': 'People & Body',
    '👩\u200d🦼\u200d➡️': 'People & Body',
    '🧑\u200d🦽': 'People & Body',
    '🧑\u200d🦽\u200d➡️': 'People & Body',
    '👨\u200d🦽': 'People & Body',
    '👨\u200d🦽\u200d➡️': 'People & Body',
    '👩\u200d🦽': 'People & Body',
    '👩\u200d🦽\u200d➡️': 'People & Body',
    '🏃': 'People & Body',
    '🏃\u200d➡️': 'People & Body',
    '💃': 'People & Body',
    '🕺': 'People & Body',
    '🕴️': 'People & Body',
    '👯': 'People & Body',
    '🧖': 'People & Body',
    '🧗': 'People & Body',
    '🤺': 'People & Body',
    '🏇': 'People & Body',
    '⛷️': 'People & Body',
    '🏂': 'People & Body',
    '🏌️': 'People & Body',
    '🏄': 'People & Body',
    '🚣': 'People & Body',
    '🏊': 'People & Body',
    '⛹️': 'People & Body',
    '🏋️': 'People & Body',
    '🚴': 'People & Body',
    '🚵': 'People & Body',
    '🤸': 'People & Body',
    '🤼': 'People & Body',
    '🤽': 'People & Body',
    '🤾': 'People & Body',
    '🤹': 'People & Body',
    '🧘': 'People & Body',
    '🛀': 'People & Body',
    '🛌': 'People & Body',
    '🧑\u200d🤝\u200d🧑': 'People & Body',
    '👭': 'People & Body',
    '👫': 'People & Body',
    '👬': 'People & Body',
    '💏': 'People & Body',
    '👩\u200d❤️\u200d💋\u200d👨': 'People & Body',
    '👨\u200d❤️\u200d💋\u200d👨': 'People & Body',
    '👩\u200d❤️\u200d💋\u200d👩': 'People & Body',
    '💑': 'People & Body',
    '👩\u200d❤️\u200d👨': 'People & Body',
    '👨\u200d❤️\u200d👨': 'People & Body',
    '👩\u200d❤️\u200d👩': 'People & Body',
    '👨\u200d👩\u200d👦': 'People & Body',
    '👨\u200d👩\u200d👧': 'People & Body',
    '👨\u200d👩\u200d👧\u200d👦': 'People & Body',
    '👨\u200d👩\u200d👦\u200d👦': 'People & Body',
    '👨\u200d👩\u200d👧\u200d👧': 'People & Body',
    '👨\u200d👨\u200d👦': 'People & Body',
    '👨\u200d👨\u200d👧': 'People & Body',
    '👨\u200d👨\u200d👧\u200d👦': 'People & Body',
    '👨\u200d👨\u200d👦\u200d👦': 'People & Body',
    '👨\u200d👨\u200d👧\u200d👧': 'People & Body',
    '👩\u200d👩\u200d👦': 'People & Body',
    '👩\u200d👩\u200d👧': 'People & Body',
    '👩\u200d👩\u200d👧\u200d👦': 'People & Body',
    '👩\u200d👩\u200d👦\u200d👦': 'People & Body',
    '👩\u200d👩\u200d👧\u200d👧': 'People & Body',
    '👨\u200d👦': 'People & Body',
    '👨\u200d👦\u200d👦': 'People & Body',
    '👨\u200d👧': 'People & Body',
    '👨\u200d👧\u200d👦': 'People & Body',
    '👨\u200d👧\u200d👧': 'People & Body',
    '👩\u200d👦': 'People & Body',
    '👩\u200d👦\u200d👦': 'People & Body',
    '👩\u200d👧': 'People & Body',
    '👩\u200d👧\u200d👦': 'People & Body',
    '👩\u200d👧\u200d👧': 'People & Body',
    '🗣️': 'People & Body',
    '👤': 'People & Body',
    '👥': 'People & Body',
    '🫂': 'People & Body',
    '👪': 'People & Body',
    '🧑\u200d🧑\u200d🧒': 'People & Body',
    '🧑\u200d🧑\u200d🧒\u200d🧒': 'People & Body',
    '🧑\u200d🧒': 'People & Body',
    '🧑\u200d🧒\u200d🧒': 'People & Body',
    '👣': 'People & Body',
    '🐵': 'Animals & Nature',
    '🐒': 'Animals & Nature',
    '🦍': 'Animals & Nature',
    '🦧': 'Animals & Nature',
    '🐶': 'Animals & Nature',
    '🐕': 'Animals & Nature',
    '🦮': 'Animals & Nature',
    '🐕\u200d🦺': 'Animals & Nature',
    '🐩': 'Animals & Nature',
    '🐺': 'Animals & Nature',
    '🦊': 'Animals & Nature',
    '🦝': 'Animals & Nature',
    '🐱': 'Animals & Nature',
    '🐈': 'Animals & Nature',
    '🐈\u200d⬛': 'Animals & Nature',
    '🦁': 'Animals & Nature',
    '🐯': 'Animals & Nature',
    '🐅': 'Animals & Nature',
    '🐆': 'Animals & Nature',
    '🐴': 'Animals & Nature',
    '🫎': 'Animals & Nature',
    '🫏': 'Animals & Nature',
    '🐎': 'Animals & Nature',
    '🦄': 'Animals & Nature',
    '🦓': 'Animals & Nature',
    '🦌': 'Animals & Nature',
    '🦬': 'Animals & Nature',
    '🐮': 'Animals & Nature',
    '🐂': 'Animals & Nature',
    '🐃': 'Animals & Nature',
    '🐄': 'Animals & Nature',
    '🐷': 'Animals & Nature',
    '🐖': 'Animals & Nature',
    '🐗': 'Animals & Nature',
    '🐽': 'Animals & Nature',
    '🐏': 'Animals & Nature',
    '🐑': 'Animals & Nature',
    '🐐': 'Animals & Nature',
    '🐪': 'Animals & Nature',
    '🐫': 'Animals & Nature',
    '🦙': 'Animals & Nature',
    '🦒': 'Animals & Nature',
    '🐘': 'Animals & Nature',
    '🦣': 'Animals & Nature',
    '🦏': 'Animals & Nature',
    '🦛': 'Animals & Nature',
    '🐭': 'Animals & Nature',
    '🐁': 'Animals & Nature',
    '🐀': 'Animals & Nature',
    '🐹': 'Animals & Nature',
    '🐰': 'Animals & Nature',
    '🐇': 'Animals & Nature',
    '🐿️': 'Animals & Nature',
    '🦫': 'Animals & Nature',
    '🦔': 'Animals & Nature',
    '🦇': 'Animals & Nature',
    '🐻': 'Animals & Nature',
    '🐻\u200d❄️': 'Animals & Nature',
    '🐨': 'Animals & Nature',
    '🐼': 'Animals & Nature',
    '🦥': 'Animals & Nature',
    '🦦': 'Animals & Nature',
    '🦨': 'Animals & Nature',
    '🦘': 'Animals & Nature',
    '🦡': 'Animals & Nature',
    '🐾': 'Animals & Nature',
    '🦃': 'Animals & Nature',
    '🐔': 'Animals & Nature',
    '🐓': 'Animals & Nature',
    '🐣': 'Animals & Nature',
    '🐤': 'Animals & Nature',
    '🐥': 'Animals & Nature',
    '🐦': 'Animals & Nature',
    '🐧': 'Animals & Nature',
    '🕊️': 'Animals & Nature',
    '🦅': 'Animals & Nature',
    '🦆': 'Animals & Nature',
    '🦢': 'Animals & Nature',
    '🦉': 'Animals & Nature',
    '🦤': 'Animals & Nature',
    '🪶': 'Animals & Nature',
    '🦩': 'Animals & Nature',
    '🦚': 'Animals & Nature',
    '🦜': 'Animals & Nature',
    '🪽': 'Animals & Nature',
    '🐦\u200d⬛': 'Animals & Nature',
    '🪿': 'Animals & Nature',
    '🐦\u200d🔥': 'Animals & Nature',
    '🐸': 'Animals & Nature',
    '🐊': 'Animals & Nature',
    '🐢': 'Animals & Nature',
    '🦎': 'Animals & Nature',
    '🐍': 'Animals & Nature',
    '🐲': 'Animals & Nature',
    '🐉': 'Animals & Nature',
    '🦕': 'Animals & Nature',
    '🦖': 'Animals & Nature',
    '🐳': 'Animals & Nature',
    '🐋': 'Animals & Nature',
    '🐬': 'Animals & Nature',
    '🦭': 'Animals & Nature',
    '🐟': 'Animals & Nature',
    '🐠': 'Animals & Nature',
    '🐡': 'Animals & Nature',
    '🦈': 'Animals & Nature',
    '🐙': 'Animals & Nature',
    '🐚': 'Animals & Nature',
    '🪸': 'Animals & Nature',
    '🪼': 'Animals & Nature',
    '🐌': 'Animals & Nature',
    '🦋': 'Animals & Nature',
    '🐛': 'Animals & Nature',
    '🐜': 'Animals & Nature',
    '🐝': 'Animals & Nature',
    '🪲': 'Animals & Nature',
    '🐞': 'Animals & Nature',
    '🦗': 'Animals & Nature',
    '🪳': 'Animals & Nature',
    '🕷️': 'Animals & Nature',
    '🕸️': 'Animals & Nature',
    '🦂': 'Animals & Nature',
    '🦟': 'Animals & Nature',
    '🪰': 'Animals & Nature',
    '🪱': 'Animals & Nature',
    '🦠': 'Animals & Nature',
    '💐': 'Animals & Nature',
    '🌸': 'Animals & Nature',
    '💮': 'Animals & Nature',
    '🪷': 'Animals & Nature',
    '🏵️': 'Animals & Nature',
    '🌹': 'Animals & Nature',
    '🥀': 'Animals & Nature',
    '🌺': 'Animals & Nature',
    '🌻': 'Animals & Nature',
    '🌼': 'Animals & Nature',
    '🌷': 'Animals & Nature',
    '🪻': 'Animals & Nature',
    '🌱': 'Animals & Nature',
    '🪴': 'Animals & Nature',
    '🌲': 'Animals & Nature',
    '🌳': 'Animals & Nature',
    '🌴': 'Animals & Nature',
    '🌵': 'Animals & Nature',
    '🌾': 'Animals & Nature',
    '🌿': 'Animals & Nature',
    '☘️': 'Animals & Nature',
    '🍀': 'Animals & Nature',
    '🍁': 'Animals & Nature',
    '🍂': 'Animals & Nature',
    '🍃': 'Animals & Nature',
    '🪹': 'Animals & Nature',
    '🪺': 'Animals & Nature',
    '🍄': 'Animals & Nature',
    '🍇': 'Food & Drink',
    '🍈': 'Food & Drink',
    '🍉': 'Food & Drink',
    '🍊': 'Food & Drink',
    '🍋': 'Food & Drink',
    '🍋\u200d🟩': 'Food & Drink',
    '🍌': 'Food & Drink',
    '🍍': 'Food & Drink',
    '🥭': 'Food & Drink',
    '🍎': 'Food & Drink',
    '🍏': 'Food & Drink',
    '🍐': 'Food & Drink',
    '🍑': 'Food & Drink',
    '🍒': 'Food & Drink',
    '🍓': 'Food & Drink',
    '🫐': 'Food & Drink',
    '🥝': 'Food & Drink',
    '🍅': 'Food & Drink',
    '🫒': 'Food & Drink',
    '🥥': 'Food & Drink',
    '🥑': 'Food & Drink',
    '🍆': 'Food & Drink',
    '🥔': 'Food & Drink',
    '🥕': 'Food & Drink',
    '🌽': 'Food & Drink',
    '🌶️': 'Food & Drink',
    '🫑': 'Food & Drink',
    '🥒': 'Food & Drink',
    '🥬': 'Food & Drink',
    '🥦': 'Food & Drink',
    '🧄': 'Food & Drink',
    '🧅': 'Food & Drink',
    '🥜': 'Food & Drink',
    '🫘': 'Food & Drink',
    '🌰': 'Food & Drink',
    '🫚': 'Food & Drink',
    '🫛': 'Food & Drink',
    '🍄\u200d🟫': 'Food & Drink',
    '🍞': 'Food & Drink',
    '🥐': 'Food & Drink',
    '🥖': 'Food & Drink',
    '🫓': 'Food & Drink',
    '🥨': 'Food & Drink',
    '🥯': 'Food & Drink',
    '🥞': 'Food & Drink',
    '🧇': 'Food & Drink',
    '🧀': 'Food & Drink',
    '🍖': 'Food & Drink',
    '🍗': 'Food & Drink',
    '🥩': 'Food & Drink',
    '🥓': 'Food & Drink',
    '🍔': 'Food & Drink',
    '🍟': 'Food & Drink',
    '🍕': 'Food & Drink',
    '🌭': 'Food & Drink',
    '🥪': 'Food & Drink',
    '🌮': 'Food & Drink',
    '🌯': 'Food & Drink',
    '🫔': 'Food & Drink',
    '🥙': 'Food & Drink',
    '🧆': 'Food & Drink',
    '🥚': 'Food & Drink',
    '🍳': 'Food & Drink',
    '🥘': 'Food & Drink',
    '🍲': 'Food & Drink',
    '🫕': 'Food & Drink',
    '🥣': 'Food & Drink',
    '🥗': 'Food & Drink',
    '🍿': 'Food & Drink',
    '🧈': 'Food & Drink',
    '🧂': 'Food & Drink',
    '🥫': 'Food & Drink',
    '🍱': 'Food & Drink',
    '🍘': 'Food & Drink',
    '🍙': 'Food & Drink',
    '🍚': 'Food & Drink',
    '🍛': 'Food & Drink',
    '🍜': 'Food & Drink',
    '🍝': 'Food & Drink',
    '🍠': 'Food & Drink',
    '🍢': 'Food & Drink',
    '🍣': 'Food & Drink',
    '🍤': 'Food & Drink',
    '🍥': 'Food & Drink',
    '🥮': 'Food & Drink',
    '🍡': 'Food & Drink',
    '🥟': 'Food & Drink',
    '🥠': 'Food & Drink',
    '🥡': 'Food & Drink',
    '🦀': 'Food & Drink',
    '🦞': 'Food & Drink',
    '🦐': 'Food & Drink',
    '🦑': 'Food & Drink',
    '🦪': 'Food & Drink',
    '🍦': 'Food & Drink',
    '🍧': 'Food & Drink',
    '🍨': 'Food & Drink',
    '🍩': 'Food & Drink',
    '🍪': 'Food & Drink',
    '🎂': 'Food & Drink',
    '🍰': 'Food & Drink',
    '🧁': 'Food & Drink',
    '🥧': 'Food & Drink',
    '🍫': 'Food & Drink',
    '🍬': 'Food & Drink',
    '🍭': 'Food & Drink',
    '🍮': 'Food & Drink',
    '🍯': 'Food & Drink',
    '🍼': 'Food & Drink',
    '🥛': 'Food & Drink',
    '☕': 'Food & Drink',
    '🫖': 'Food & Drink',
    '🍵': 'Food & Drink',
    '🍶': 'Food & Drink',
    '🍾': 'Food & Drink',
    '🍷': 'Food & Drink',
    '🍸': 'Food & Drink',
    '🍹': 'Food & Drink',
    '🍺': 'Food & Drink',
    '🍻': 'Food & Drink',
    '🥂': 'Food & Drink',
    '🥃': 'Food & Drink',
    '🫗': 'Food & Drink',
    '🥤': 'Food & Drink',
    '🧋': 'Food & Drink',
    '🧃': 'Food & Drink',
    '🧉': 'Food & Drink',
    '🧊': 'Food & Drink',
    '🥢': 'Food & Drink',
    '🍽️': 'Food & Drink',
    '🍴': 'Food & Drink',
    '🥄': 'Food & Drink',
    '🔪': 'Food & Drink',
    '🫙': 'Food & Drink',
    '🏺': 'Food & Drink',
    '🌍': 'Travel & Places',
    '🌎': 'Travel & Places',
    '🌏': 'Travel & Places',
    '🌐': 'Travel & Places',
    '🗺️': 'Travel & Places',
    '🗾': 'Travel & Places',
    '🧭': 'Travel & Places',
    '🏔️': 'Travel & Places',
    '⛰️': 'Travel & Places',
    '🌋': 'Travel & Places',
    '🗻': 'Travel & Places',
    '🏕️': 'Travel & Places',
    '🏖️': 'Travel & Places',
    '🏜️': 'Travel & Places',
    '🏝️': 'Travel & Places',
    '🏞️': 'Travel & Places',
    '🏟️': 'Travel & Places',
    '🏛️': 'Travel & Places',
    '🏗️': 'Travel & Places',
    '🧱': 'Travel & Places',
    '🪨': 'Travel & Places',
    '🪵': 'Travel & Places',
    '🛖': 'Travel & Places',
    '🏘️': 'Travel & Places',
    '🏚️': 'Travel & Places',
    '🏠': 'Travel & Places',
    '🏡': 'Travel & Places',
    '🏢': 'Travel & Places',
    '🏣': 'Travel & Places',
    '🏤': 'Travel & Places',
    '🏥': 'Travel & Places',
    '🏦': 'Travel & Places',
    '🏨': 'Travel & Places',
    '🏩': 'Travel & Places',
    '🏪': 'Travel & Places',
    '🏫': 'Travel & Places',
    '🏬': 'Travel & Places',
    '🏭': 'Travel & Places',
    '🏯': 'Travel & Places',
    '🏰': 'Travel & Places',
    '💒': 'Travel & Places',
    '🗼': 'Travel & Places',
    '🗽': 'Travel & Places',
    '⛪': 'Travel & Places',
    '🕌': 'Travel & Places',
    '🛕': 'Travel & Places',
    '🕍': 'Travel & Places',
    '⛩️': 'Travel & Places',
    '🕋': 'Travel & Places',
    '⛲': 'Travel & Places',
    '⛺': 'Travel & Places',
    '🌁': 'Travel & Places',
    '🌃': 'Travel & Places',
    '🏙️': 'Travel & Places',
    '🌄': 'Travel & Places',
    '🌅': 'Travel & Places',
    '🌆': 'Travel & Places',
    '🌇': 'Travel & Places',
    '🌉': 'Travel & Places',
    '♨️': 'Travel & Places',
    '🎠': 'Travel & Places',
    '🛝': 'Travel & Places',
    '🎡': 'Travel & Places',
    '🎢': 'Travel & Places',
    '💈': 'Travel & Places',
    '🎪': 'Travel & Places',
    '🚂': 'Travel & Places',
    '🚃': 'Travel & Places',
    '🚄': 'Travel & Places',
    '🚅': 'Travel & Places',
    '🚆': 'Travel & Places',
    '🚇': 'Travel & Places',
    '🚈': 'Travel & Places',
    '🚉': 'Travel & Places',
    '🚊': 'Travel & Places',
    '🚝': 'Travel & Places',
    '🚞': 'Travel & Places',
    '🚋': 'Travel & Places',
    '🚌': 'Travel & Places',
    '🚍': 'Travel & Places',
    '🚎': 'Travel & Places',
    '🚐': 'Travel & Places',
    '🚑': 'Travel & Places',
    '🚒': 'Travel & Places',
    '🚓': 'Travel & Places',
    '🚔': 'Travel & Places',
    '🚕': 'Travel & Places',
    '🚖': 'Travel & Places',
    '🚗': 'Travel & Places',
    '🚘': 'Travel & Places',
    '🚙': 'Travel & Places',
    '🛻': 'Travel & Places',
    '🚚': 'Travel & Places',
    '🚛': 'Travel & Places',
    '🚜': 'Travel & Places',
    '🏎️': 'Travel & Places',
    '🏍️': 'Travel & Places',
    '🛵': 'Travel & Places',
    '🦽': 'Travel & Places',
    '🦼': 'Travel & Places',
    '🛺': 'Travel & Places',
    '🚲': 'Travel & Places',
    '🛴': 'Travel & Places',
    '🛹': 'Travel & Places',
    '🛼': 'Travel & Places',
    '🚏': 'Travel & Places',
    '🛣️': 'Travel & Places',
    '🛤️': 'Travel & Places',
    '🛢️': 'Travel & Places',
    '⛽': 'Travel & Places',
    '🛞': 'Travel & Places',
    '🚨': 'Travel & Places',
    '🚥': 'Travel & Places',
    '🚦': 'Travel & Places',
    '🛑': 'Travel & Places',
    '🚧': 'Travel & Places',
    '⚓': 'Travel & Places',
    '🛟': 'Travel & Places',
    '⛵': 'Travel & Places',
    '🛶': 'Travel & Places',
    '🚤': 'Travel & Places',
    '🛳️': 'Travel & Places',
    '⛴️': 'Travel & Places',
    '🛥️': 'Travel & Places',
    '🚢': 'Travel & Places',
    '✈️': 'Travel & Places',
    '🛩️': 'Travel & Places',
    '🛫': 'Travel & Places',
    '🛬': 'Travel & Places',
    '🪂': 'Travel & Places',
    '💺': 'Travel & Places',
    '🚁': 'Travel & Places',
    '🚟': 'Travel & Places',
    '🚠': 'Travel & Places',
    '🚡': 'Travel & Places',
    '🛰️': 'Travel & Places',
    '🚀': 'Travel & Places',
    '🛸': 'Travel & Places',
    '🛎️': 'Travel & Places',
    '🧳': 'Travel & Places',
    '⌛': 'Travel & Places',
    '⏳': 'Travel & Places',
    '⌚': 'Travel & Places',
    '⏰': 'Travel & Places',
    '⏱️': 'Travel & Places',
    '⏲️': 'Travel & Places',
    '🕰️': 'Travel & Places',
    '🕛': 'Travel & Places',
    '🕧': 'Travel & Places',
    '🕐': 'Travel & Places',
    '🕜': 'Travel & Places',
    '🕑': 'Travel & Places',
    '🕝': 'Travel & Places',
    '🕒': 'Travel & Places',
    '🕞': 'Travel & Places',
    '🕓': 'Travel & Places',
    '🕟': 'Travel & Places',
    '🕔': 'Travel & Places',
    '🕠': 'Travel & Places',
    '🕕': 'Travel & Places',
    '🕡': 'Travel & Places',
    '🕖': 'Travel & Places',
    '🕢': 'Travel & Places',
    '🕗': 'Travel & Places',
    '🕣': 'Travel & Places',
    '🕘': 'Travel & Places',
    '🕤': 'Travel & Places',
    '🕙': 'Travel & Places',
    '🕥': 'Travel & Places',
    '🕚': 'Travel & Places',
    '🕦': 'Travel & Places',
    '🌑': 'Travel & Places',
    '🌒': 'Travel & Places',
    '🌓': 'Travel & Places',
    '🌔': 'Travel & Places',
    '🌕': 'Travel & Places',
    '🌖': 'Travel & Places',
    '🌗': 'Travel & Places',
    '🌘': 'Travel & Places',
    '🌙': 'Travel & Places',
    '🌚': 'Travel & Places',
    '🌛': 'Travel & Places',
    '🌜': 'Travel & Places',
    '🌡️': 'Travel & Places',
    '☀️': 'Travel & Places',
    '🌝': 'Travel & Places',
    '🌞': 'Travel & Places',
    '🪐': 'Travel & Places',
    '⭐': 'Travel & Places',
    '🌟': 'Travel & Places',
    '🌠': 'Travel & Places',
    '🌌': 'Travel & Places',
    '☁️': 'Travel & Places',
    '⛅': 'Travel & Places',
    '⛈️': 'Travel & Places',
    '🌤️': 'Travel & Places',
    '🌥️': 'Travel & Places',
    '🌦️': 'Travel & Places',
    '🌧️': 'Travel & Places',
    '🌨️': 'Travel & Places',
    '🌩️': 'Travel & Places',
    '🌪️': 'Travel & Places',
    '🌫️': 'Travel & Places',
    '🌬️': 'Travel & Places',
    '🌀': 'Travel & Places',
    '🌈': 'Travel & Places',
    '🌂': 'Travel & Places',
    '☂️': 'Travel & Places',
    '☔': 'Travel & Places',
    '⛱️': 'Travel & Places',
    '⚡': 'Travel & Places',
    '❄️': 'Travel & Places',
    '☃️': 'Travel & Places',
    '⛄': 'Travel & Places',
    '☄️': 'Travel & Places',
    '🔥': 'Travel & Places',
    '💧': 'Travel & Places',
    '🌊': 'Travel & Places',
    '🎃': 'Activities',
    '🎄': 'Activities',
    '🎆': 'Activities',
    '🎇': 'Activities',
    '🧨': 'Activities',
    '✨': 'Activities',
    '🎈': 'Activities',
    '🎉': 'Activities',
    '🎊': 'Activities',
    '🎋': 'Activities',
    '🎍': 'Activities',
    '🎎': 'Activities',
    '🎏': 'Activities',
    '🎐': 'Activities',
    '🎑': 'Activities',
    '🧧': 'Activities',
    '🎀': 'Activities',
    '🎁': 'Activities',
    '🎗️': 'Activities',
    '🎟️': 'Activities',
    '🎫': 'Activities',
    '🎖️': 'Activities',
    '🏆': 'Activities',
    '🏅': 'Activities',
    '🥇': 'Activities',
    '🥈': 'Activities',
    '🥉': 'Activities',
    '⚽': 'Activities',
    '⚾': 'Activities',
    '🥎': 'Activities',
    '🏀': 'Activities',
    '🏐': 'Activities',
    '🏈': 'Activities',
    '🏉': 'Activities',
    '🎾': 'Activities',
    '🥏': 'Activities',
    '🎳': 'Activities',
    '🏏': 'Activities',
    '🏑': 'Activities',
    '🏒': 'Activities',
    '🥍': 'Activities',
    '🏓': 'Activities',
    '🏸': 'Activities',
    '🥊': 'Activities',
    '🥋': 'Activities',
    '🥅': 'Activities',
    '⛳': 'Activities',
    '⛸️': 'Activities',
    '🎣': 'Activities',
    '🤿': 'Activities',
    '🎽': 'Activities',
    '🎿': 'Activities',
    '🛷': 'Activities',
    '🥌': 'Activities',
    '🎯': 'Activities',
    '🪀': 'Activities',
    '🪁': 'Activities',
    '🔫': 'Activities',
    '🎱': 'Activities',
    '🔮': 'Activities',
    '🪄': 'Activities',
    '🎮': 'Activities',
    '🕹️': 'Activities',
    '🎰': 'Activities',
    '🎲': 'Activities',
    '🧩': 'Activities',
    '🧸': 'Activities',
    '🪅': 'Activities',
    '🪩': 'Activities',
    '🪆': 'Activities',
    '♠️': 'Activities',
    '♥️': 'Activities',
    '♦️': 'Activities',
    '♣️': 'Activities',
    '♟️': 'Activities',
    '🃏': 'Activities',
    '🀄': 'Activities',
    '🎴': 'Activities',
    '🎭': 'Activities',
    '🖼️': 'Activities',
    '🎨': 'Activities',
    '🧵': 'Activities',
    '🪡': 'Activities',
    '🧶': 'Activities',
    '🪢': 'Activities',
    '👓': 'Objects',
    '🕶️': 'Objects',
    '🥽': 'Objects',
    '🥼': 'Objects',
    '🦺': 'Objects',
    '👔': 'Objects',
    '👕': 'Objects',
    '👖': 'Objects',
    '🧣': 'Objects',
    '🧤': 'Objects',
    '🧥': 'Objects',
    '🧦': 'Objects',
    '👗': 'Objects',
    '👘': 'Objects',
    '🥻': 'Objects',
    '🩱': 'Objects',
    '🩲': 'Objects',
    '🩳': 'Objects',
    '👙': 'Objects',
    '👚': 'Objects',
    '🪭': 'Objects',
    '👛': 'Objects',
    '👜': 'Objects',
    '👝': 'Objects',
    '🛍️': 'Objects',
    '🎒': 'Objects',
    '🩴': 'Objects',
    '👞': 'Objects',
    '👟': 'Objects',
    '🥾': 'Objects',
    '🥿': 'Objects',
    '👠': 'Objects',
    '👡': 'Objects',
    '🩰': 'Objects',
    '👢': 'Objects',
    '🪮': 'Objects',
    '👑': 'Objects',
    '👒': 'Objects',
    '🎩': 'Objects',
    '🎓': 'Objects',
    '🧢': 'Objects',
    '🪖': 'Objects',
    '⛑️': 'Objects',
    '📿': 'Objects',
    '💄': 'Objects',
    '💍': 'Objects',
    '💎': 'Objects',
    '🔇': 'Objects',
    '🔈': 'Objects',
    '🔉': 'Objects',
    '🔊': 'Objects',
    '📢': 'Objects',
    '📣': 'Objects',
    '📯': 'Objects',
    '🔔': 'Objects',
    '🔕': 'Objects',
    '🎼': 'Objects',
    '🎵': 'Objects',
    '🎶': 'Objects',
    '🎙️': 'Objects',
    '🎚️': 'Objects',
    '🎛️': 'Objects',
    '🎤': 'Objects',
    '🎧': 'Objects',
    '📻': 'Objects',
    '🎷': 'Objects',
    '🪗': 'Objects',
    '🎸': 'Objects',
    '🎹': 'Objects',
    '🎺': 'Objects',
    '🎻': 'Objects',
    '🪕': 'Objects',
    '🥁': 'Objects',
    '🪘': 'Objects',
    '🪇': 'Objects',
    '🪈': 'Objects',
    '📱': 'Objects',
    '📲': 'Objects',
    '☎️': 'Objects',
    '📞': 'Objects',
    '📟': 'Objects',
    '📠': 'Objects',
    '🔋': 'Objects',
    '🪫': 'Objects',
    '🔌': 'Objects',
    '💻': 'Objects',
    '🖥️': 'Objects',
    '🖨️': 'Objects',
    '⌨️': 'Objects',
    '🖱️': 'Objects',
    '🖲️': 'Objects',
    '💽': 'Objects',
    '💾': 'Objects',
    '💿': 'Objects',
    '📀': 'Objects',
    '🧮': 'Objects',
    '🎥': 'Objects',
    '🎞️': 'Objects',
    '📽️': 'Objects',
    '🎬': 'Objects',
    '📺': 'Objects',
    '📷': 'Objects',
    '📸': 'Objects',
    '📹': 'Objects',
    '📼': 'Objects',
    '🔍': 'Objects',
    '🔎': 'Objects',
    '🕯️': 'Objects',
    '💡': 'Objects',
    '🔦': 'Objects',
    '🏮': 'Objects',
    '🪔': 'Objects',
    '📔': 'Objects',
    '📕': 'Objects',
    '📖': 'Objects',
    '📗': 'Objects',
    '📘': 'Objects',
    '📙': 'Objects',
    '📚': 'Objects',
    '📓': 'Objects',
    '📒': 'Objects',
    '📃': 'Objects',
    '📜': 'Objects',
    '📄': 'Objects',
    '📰': 'Objects',
    '🗞️': 'Objects',
    '📑': 'Objects',
    '🔖': 'Objects',
    '🏷️': 'Objects',
    '💰': 'Objects',
    '🪙': 'Objects',
    '💴': 'Objects',
    '💵': 'Objects',
    '💶': 'Objects',
    '💷': 'Objects',
    '💸': 'Objects',
    '💳': 'Objects',
    '🧾': 'Objects',
    '💹': 'Objects',
    '✉️': 'Objects',
    '📧': 'Objects',
    '📨': 'Objects',
    '📩': 'Objects',
    '📤': 'Objects',
    '📥': 'Objects',
    '📦': 'Objects',
    '📫': 'Objects',
    '📪': 'Objects',
    '📬': 'Objects',
    '📭': 'Objects',
    '📮': 'Objects',
    '🗳️': 'Objects',
    '✏️': 'Objects',
    '✒️': 'Objects',
    '🖋️': 'Objects',
    '🖊️': 'Objects',
    '🖌️': 'Objects',
    '🖍️': 'Objects',
    '📝': 'Objects',
    '💼': 'Objects',
    '📁': 'Objects',
    '📂': 'Objects',
    '🗂️': 'Objects',
    '📅': 'Objects',
    '📆': 'Objects',
    '🗒️': 'Objects',
    '🗓️': 'Objects',
    '📇': 'Objects',
    '📈': 'Objects',
    '📉': 'Objects',
    '📊': 'Objects',
    '📋': 'Objects',
    '📌': 'Objects',
    '📍': 'Objects',
    '📎': 'Objects',
    '🖇️': 'Objects',
    '📏': 'Objects',
    '📐': 'Objects',
    '✂️': 'Objects',
    '🗃️': 'Objects',
    '🗄️': 'Objects',
    '🗑️': 'Objects',
    '🔒': 'Objects',
    '🔓': 'Objects',
    '🔏': 'Objects',
    '🔐': 'Objects',
    '🔑': 'Objects',
    '🗝️': 'Objects',
    '🔨': 'Objects',
    '🪓': 'Objects',
    '⛏️': 'Objects',
    '⚒️': 'Objects',
    '🛠️': 'Objects',
    '🗡️': 'Objects',
    '⚔️': 'Objects',
    '💣': 'Objects',
    '🪃': 'Objects',
    '🏹': 'Objects',
    '🛡️': 'Objects',
    '🪚': 'Objects',
    '🔧': 'Objects',
    '🪛': 'Objects',
    '🔩': 'Objects',
    '⚙️': 'Objects',
    '🗜️': 'Objects',
    '⚖️': 'Objects',
    '🦯': 'Objects',
    '🔗': 'Objects',
    '⛓️\u200d💥': 'Objects',
    '⛓️': 'Objects',
    '🪝': 'Objects',
    '🧰': 'Objects',
    '🧲': 'Objects',
    '🪜': 'Objects',
    '⚗️': 'Objects',
    '🧪': 'Objects',
    '🧫': 'Objects',
    '🧬': 'Objects',
    '🔬': 'Objects',
    '🔭': 'Objects',
    '📡': 'Objects',
    '💉': 'Objects',
    '🩸': 'Objects',
    '💊': 'Objects',
    '🩹': 'Objects',
    '🩼': 'Objects',
    '🩺': 'Objects',
    '🩻': 'Objects',
    '🚪': 'Objects',
    '🛗': 'Objects',
    '🪞': 'Objects',
    '🪟': 'Objects',
    '🛏️': 'Objects',
    '🛋️': 'Objects',
    '🪑': 'Objects',
    '🚽': 'Objects',
    '🪠': 'Objects',
    '🚿': 'Objects',
    '🛁': 'Objects',
    '🪤': 'Objects',
    '🪒': 'Objects',
    '🧴': 'Objects',
    '🧷': 'Objects',
    '🧹': 'Objects',
    '🧺': 'Objects',
    '🧻': 'Objects',
    '🪣': 'Objects',
    '🧼': 'Objects',
    '🫧': 'Objects',
    '🪥': 'Objects',
    '🧽': 'Objects',
    '🧯': 'Objects',
    '🛒': 'Objects',
    '🚬': 'Objects',
    '⚰️': 'Objects',
    '🪦': 'Objects',
    '⚱️': 'Objects',
    '🧿': 'Objects',
    '🪬': 'Objects',
    '🗿': 'Objects',
    '🪧': 'Objects',
    '🪪': 'Objects',
    '🏧': 'Symbols',
    '🚮': 'Symbols',
    '🚰': 'Symbols',
    '♿': 'Symbols',
    '🚹': 'Symbols',
    '🚺': 'Symbols',
    '🚻': 'Symbols',
    '🚼': 'Symbols',
    '🚾': 'Symbols',
    '🛂': 'Symbols',
    '🛃': 'Symbols',
    '🛄': 'Symbols',
    '🛅': 'Symbols',
    '⚠️': 'Symbols',
    '🚸': 'Symbols',
    '⛔': 'Symbols',
    '🚫': 'Symbols',
    '🚳': 'Symbols',
    '🚭': 'Symbols',
    '🚯': 'Symbols',
    '🚱': 'Symbols',
    '🚷': 'Symbols',
    '📵': 'Symbols',
    '🔞': 'Symbols',
    '☢️': 'Symbols',
    '☣️': 'Symbols',
    '⬆️': 'Symbols',
    '↗️': 'Symbols',
    '➡️': 'Symbols',
    '↘️': 'Symbols',
    '⬇️': 'Symbols',
    '↙️': 'Symbols',
    '⬅️': 'Symbols',
    '↖️': 'Symbols',
    '↕️': 'Symbols',
    '↔️': 'Symbols',
    '↩️': 'Symbols',
    '↪️': 'Symbols',
    '⤴️': 'Symbols',
    '⤵️': 'Symbols',
    '🔃': 'Symbols',
    '🔄': 'Symbols',
    '🔙': 'Symbols',
    '🔚': 'Symbols',
    '🔛': 'Symbols',
    '🔜': 'Symbols',
    '🔝': 'Symbols',
    '🛐': 'Symbols',
    '⚛️': 'Symbols',
    '🕉️': 'Symbols',
    '✡️': 'Symbols',
    '☸️': 'Symbols',
    '☯️': 'Symbols',
    '✝️': 'Symbols',
    '☦️': 'Symbols',
    '☪️': 'Symbols',
    '☮️': 'Symbols',
    '🕎': 'Symbols',
    '🔯': 'Symbols',
    '🪯': 'Symbols',
    '♈': 'Symbols',
    '♉': 'Symbols',
    '♊': 'Symbols',
    '♋': 'Symbols',
    '♌': 'Symbols',
    '♍': 'Symbols',
    '♎': 'Symbols',
    '♏': 'Symbols',
    '♐': 'Symbols',
    '♑': 'Symbols',
    '♒': 'Symbols',
    '♓': 'Symbols',
    '⛎': 'Symbols',
    '🔀': 'Symbols',
    '🔁': 'Symbols',
    '🔂': 'Symbols',
    '▶️': 'Symbols',
    '⏩': 'Symbols',
    '⏭️': 'Symbols',
    '⏯️': 'Symbols',
    '◀️': 'Symbols',
    '⏪': 'Symbols',
    '⏮️': 'Symbols',
    '🔼': 'Symbols',
    '⏫': 'Symbols',
    '🔽': 'Symbols',
    '⏬': 'Symbols',
    '⏸️': 'Symbols',
    '⏹️': 'Symbols',
    '⏺️': 'Symbols',
    '⏏️': 'Symbols',
    '🎦': 'Symbols',
    '🔅': 'Symbols',
    '🔆': 'Symbols',
    '📶': 'Symbols',
    '🛜': 'Symbols',
    '📳': 'Symbols',
    '📴': 'Symbols',
    '⚧️': 'Symbols',
    '✖️': 'Symbols',
    '➕': 'Symbols',
    '➖': 'Symbols',
    '➗': 'Symbols',
    '🟰': 'Symbols',
    '♾️': 'Symbols',
    '‼️': 'Symbols',
    '⁉️': 'Symbols',
    '❓': 'Symbols',
    '❔': 'Symbols',
    '❕': 'Symbols',
    '❗': 'Symbols',
    '〰️': 'Symbols',
    '💱': 'Symbols',
    '💲': 'Symbols',
    '⚕️': 'Symbols',
    '♻️': 'Symbols',
    '⚜️': 'Symbols',
    '🔱': 'Symbols',
    '📛': 'Symbols',
    '🔰': 'Symbols',
    '⭕': 'Symbols',
    '✅': 'Symbols',
    '☑️': 'Symbols',
    '✔️': 'Symbols',
    '❌': 'Symbols',
    '❎': 'Symbols',
    '➰': 'Symbols',
    '➿': 'Symbols',
    '〽️': 'Symbols',
    '✳️': 'Symbols',
    '✴️': 'Symbols',
    '❇️': 'Symbols',
    '©️': 'Symbols',
    '®️': 'Symbols',
    '™️': 'Symbols',
    '#️⃣': 'Symbols',
    '*️⃣': 'Symbols',
    '0️⃣': 'Symbols',
    '1️⃣': 'Symbols',
    '2️⃣': 'Symbols',
    '3️⃣': 'Symbols',
    '4️⃣': 'Symbols',
    '5️⃣': 'Symbols',
    '6️⃣': 'Symbols',
    '7️⃣': 'Symbols',
    '8️⃣': 'Symbols',
    '9️⃣': 'Symbols',
    '🔟': 'Symbols',
    '🔠': 'Symbols',
    '🔡': 'Symbols',
    '🔢': 'Symbols',
    '🔣': 'Symbols',
    '🔤': 'Symbols',
    '🅰️': 'Symbols',
    '🆎': 'Symbols',
    '🅱️': 'Symbols',
    '🆑': 'Symbols',
    '🆒': 'Symbols',
    '🆓': 'Symbols',
    'ℹ️': 'Symbols',
    '🆔': 'Symbols',
    'Ⓜ️': 'Symbols',
    '🆕': 'Symbols',
    '🆖': 'Symbols',
    '🅾️': 'Symbols',
    '🆗': 'Symbols',
    '🅿️': 'Symbols',
    '🆘': 'Symbols',
    '🆙': 'Symbols',
    '🆚': 'Symbols',
    '🈁': 'Symbols',
    '🈂️': 'Symbols',
    '🈷️': 'Symbols',
    '🈶': 'Symbols',
    '🈯': 'Symbols',
    '🉐': 'Symbols',
    '🈹': 'Symbols',
    '🈚': 'Symbols',
    '🈲': 'Symbols',
    '🉑': 'Symbols',
    '🈸': 'Symbols',
    '🈴': 'Symbols',
    '🈳': 'Symbols',
    '㊗️': 'Symbols',
    '㊙️': 'Symbols',
    '🈺': 'Symbols',
    '🈵': 'Symbols',
    '🔴': 'Symbols',
    '🟠': 'Symbols',
    '🟡': 'Symbols',
    '🟢': 'Symbols',
    '🔵': 'Symbols',
    '🟣': 'Symbols',
    '🟤': 'Symbols',
    '⚫': 'Symbols',
    '⚪': 'Symbols',
    '🟥': 'Symbols',
    '🟧': 'Symbols',
    '🟨': 'Symbols',
    '🟩': 'Symbols',
    '🟦': 'Symbols',
    '🟪': 'Symbols',
    '🟫': 'Symbols',
    '⬛': 'Symbols',
    '⬜': 'Symbols',
    '◼️': 'Symbols',
    '◻️': 'Symbols',
    '◾': 'Symbols',
    '◽': 'Symbols',
    '▪️': 'Symbols',
    '▫️': 'Symbols',
    '🔶': 'Symbols',
    '🔷': 'Symbols',
    '🔸': 'Symbols',
    '🔹': 'Symbols',
    '🔺': 'Symbols',
    '🔻': 'Symbols',
    '💠': 'Symbols',
    '🔘': 'Symbols',
    '🔳': 'Symbols',
    '🔲': 'Symbols',
    '🏁': 'Flags',
    '🚩': 'Flags',
    '🎌': 'Flags',
    '🏴': 'Flags',
    '🏳️': 'Flags',
    '🏳️\u200d🌈': 'Flags',
    '🏳️\u200d⚧️': 'Flags',
    '🏴\u200d☠️': 'Flags',
    '🇦🇨': 'Flags',
    '🇦🇩': 'Flags',
    '🇦🇪': 'Flags',
    '🇦🇫': 'Flags',
    '🇦🇬': 'Flags',
    '🇦🇮': 'Flags',
    '🇦🇱': 'Flags',
    '🇦🇲': 'Flags',
    '🇦🇴': 'Flags',
    '🇦🇶': 'Flags',
    '🇦🇷': 'Flags',
    '🇦🇸': 'Flags',
    '🇦🇹': 'Flags',
    '🇦🇺': 'Flags',
    '🇦🇼': 'Flags',
    '🇦🇽': 'Flags',
    '🇦🇿': 'Flags',
    '🇧🇦': 'Flags',
    '🇧🇧': 'Flags',
    '🇧🇩': 'Flags',
    '🇧🇪': 'Flags',
    '🇧🇫': 'Flags',
    '🇧🇬': 'Flags',
    '🇧🇭': 'Flags',
    '🇧🇮': 'Flags',
    '🇧🇯': 'Flags',
    '🇧🇱': 'Flags',
    '🇧🇲': 'Flags',
    '🇧🇳': 'Flags',
    '🇧🇴': 'Flags',
    '🇧🇶': 'Flags',
    '🇧🇷': 'Flags',
    '🇧🇸': 'Flags',
    '🇧🇹': 'Flags',
    '🇧🇻': 'Flags',
    '🇧🇼': 'Flags',
    '🇧🇾': 'Flags',
    '🇧🇿': 'Flags',
    '🇨🇦': 'Flags',
    '🇨🇨': 'Flags',
    '🇨🇩': 'Flags',
    '🇨🇫': 'Flags',
    '🇨🇬': 'Flags',
    '🇨🇭': 'Flags',
    '🇨🇮': 'Flags',
    '🇨🇰': 'Flags',
    '🇨🇱': 'Flags',
    '🇨🇲': 'Flags',
    '🇨🇳': 'Flags',
    '🇨🇴': 'Flags',
    '🇨🇵': 'Flags',
    '🇨🇷': 'Flags',
    '🇨🇺': 'Flags',
    '🇨🇻': 'Flags',
    '🇨🇼': 'Flags',
    '🇨🇽': 'Flags',
    '🇨🇾': 'Flags',
    '🇨🇿': 'Flags',
    '🇩🇪': 'Flags',
    '🇩🇬': 'Flags',
    '🇩🇯': 'Flags',
    '🇩🇰': 'Flags',
    '🇩🇲': 'Flags',
    '🇩🇴': 'Flags',
    '🇩🇿': 'Flags',
    '🇪🇦': 'Flags',
    '🇪🇨': 'Flags',
    '🇪🇪': 'Flags',
    '🇪🇬': 'Flags',
    '🇪🇭': 'Flags',
    '🇪🇷': 'Flags',
    '🇪🇸': 'Flags',
    '🇪🇹': 'Flags',
    '🇪🇺': 'Flags',
    '🇫🇮': 'Flags',
    '🇫🇯': 'Flags',
    '🇫🇰': 'Flags',
    '🇫🇲': 'Flags',
    '🇫🇴': 'Flags',
    '🇫🇷': 'Flags',
    '🇬🇦': 'Flags',
    '🇬🇧': 'Flags',
    '🇬🇩': 'Flags',
    '🇬🇪': 'Flags',
    '🇬🇫': 'Flags',
    '🇬🇬': 'Flags',
    '🇬🇭': 'Flags',
    '🇬🇮': 'Flags',
    '🇬🇱': 'Flags',
    '🇬🇲': 'Flags',
    '🇬🇳': 'Flags',
    '🇬🇵': 'Flags',
    '🇬🇶': 'Flags',
    '🇬🇷': 'Flags',
    '🇬🇸': 'Flags',
    '🇬🇹': 'Flags',
    '🇬🇺': 'Flags',
    '🇬🇼': 'Flags',
    '🇬🇾': 'Flags',
    '🇭🇰': 'Flags',
    '🇭🇲': 'Flags',
    '🇭🇳': 'Flags',
    '🇭🇷': 'Flags',
    '🇭🇹': 'Flags',
    '🇭🇺': 'Flags',
    '🇮🇨': 'Flags',
    '🇮🇩': 'Flags',
    '🇮🇪': 'Flags',
    '🇮🇱': 'Flags',
    '🇮🇲': 'Flags',
    '🇮🇳': 'Flags',
    '🇮🇴': 'Flags',
    '🇮🇶': 'Flags',
    '🇮🇷': 'Flags',
    '🇮🇸': 'Flags',
    '🇮🇹': 'Flags',
    '🇯🇪': 'Flags',
    '🇯🇲': 'Flags',
    '🇯🇴': 'Flags',
    '🇯🇵': 'Flags',
    '🇰🇪': 'Flags',
    '🇰🇬': 'Flags',
    '🇰🇭': 'Flags',
    '🇰🇮': 'Flags',
    '🇰🇲': 'Flags',
    '🇰🇳': 'Flags',
    '🇰🇵': 'Flags',
    '🇰🇷': 'Flags',
    '🇰🇼': 'Flags',
    '🇰🇾': 'Flags',
    '🇰🇿': 'Flags',
    '🇱🇦': 'Flags',
    '🇱🇧': 'Flags',
    '🇱🇨': 'Flags',
    '🇱🇮': 'Flags',
    '🇱🇰': 'Flags',
    '🇱🇷': 'Flags',
    '🇱🇸': 'Flags',
    '🇱🇹': 'Flags',
    '🇱🇺': 'Flags',
    '🇱🇻': 'Flags',
    '🇱🇾': 'Flags',
    '🇲🇦': 'Flags',
    '🇲🇨': 'Flags',
    '🇲🇩': 'Flags',
    '🇲🇪': 'Flags',
    '🇲🇫': 'Flags',
    '🇲🇬': 'Flags',
    '🇲🇭': 'Flags',
    '🇲🇰': 'Flags',
    '🇲🇱': 'Flags',
    '🇲🇲': 'Flags',
    '🇲🇳': 'Flags',
    '🇲🇴': 'Flags',
    '🇲🇵': 'Flags',
    '🇲🇶': 'Flags',
    '🇲🇷': 'Flags',
    '🇲🇸': 'Flags',
    '🇲🇹': 'Flags',
    '🇲🇺': 'Flags',
    '🇲🇻': 'Flags',
    '🇲🇼': 'Flags',
    '🇲🇽': 'Flags',
    '🇲🇾': 'Flags',
    '🇲🇿': 'Flags',
    '🇳🇦': 'Flags',
    '🇳🇨': 'Flags',
    '🇳🇪': 'Flags',
    '🇳🇫': 'Flags',
    '🇳🇬': 'Flags',
    '🇳🇮': 'Flags',
    '🇳🇱': 'Flags',
    '🇳🇴': 'Flags',
    '🇳🇵': 'Flags',
    '🇳🇷': 'Flags',
    '🇳🇺': 'Flags',
    '🇳🇿': 'Flags',
    '🇴🇲': 'Flags',
    '🇵🇦': 'Flags',
    '🇵🇪': 'Flags',
    '🇵🇫': 'Flags',
    '🇵🇬': 'Flags',
    '🇵🇭': 'Flags',
    '🇵🇰': 'Flags',
    '🇵🇱': 'Flags',
    '🇵🇲': 'Flags',
    '🇵🇳': 'Flags',
    '🇵🇷': 'Flags',
    '🇵🇸': 'Flags',
    '🇵🇹': 'Flags',
    '🇵🇼': 'Flags',
    '🇵🇾': 'Flags',
    '🇶🇦': 'Flags',
    '🇷🇪': 'Flags',
    '🇷🇴': 'Flags',
    '🇷🇸': 'Flags',
    '🇷🇺': 'Flags',
    '🇷🇼': 'Flags',
    '🇸🇦': 'Flags',
    '🇸🇧': 'Flags',
    '🇸🇨': 'Flags',
    '🇸🇩': 'Flags',
    '🇸🇪': 'Flags',
    '🇸🇬': 'Flags',
    '🇸🇭': 'Flags',
    '🇸🇮': 'Flags',
    '🇸🇯': 'Flags',
    '🇸🇰': 'Flags',
    '🇸🇱': 'Flags',
    '🇸🇲': 'Flags',
    '🇸🇳': 'Flags',
    '🇸🇴': 'Flags',
    '🇸🇷': 'Flags',
    '🇸🇸': 'Flags',
    '🇸🇹': 'Flags',
    '🇸🇻': 'Flags',
    '🇸🇽': 'Flags',
    '🇸🇾': 'Flags',
    '🇸🇿': 'Flags',
    '🇹🇦': 'Flags',
    '🇹🇨': 'Flags',
    '🇹🇩': 'Flags',
    '🇹🇫': 'Flags',
    '🇹🇬': 'Flags',
    '🇹🇭': 'Flags',
    '🇹🇯': 'Flags',
    '🇹🇰': 'Flags',
    '🇹🇱': 'Flags',
    '🇹🇲': 'Flags',
    '🇹🇳': 'Flags',
    '🇹🇴': 'Flags',
    '🇹🇷': 'Flags',
    '🇹🇹': 'Flags',
    '🇹🇻': 'Flags',
    '🇹🇼': 'Flags',
    '🇹🇿': 'Flags',
    '🇺🇦': 'Flags',
    '🇺🇬': 'Flags',
    '🇺🇲': 'Flags',
    '🇺🇳': 'Flags',
    '🇺🇸': 'Flags',
    '🇺🇾': 'Flags',
    '🇺🇿': 'Flags',
    '🇻🇦': 'Flags',
    '🇻🇨': 'Flags',
    '🇻🇪': 'Flags',
    '🇻🇬': 'Flags',
    '🇻🇮': 'Flags',
    '🇻🇳': 'Flags',
    '🇻🇺': 'Flags',
    '🇼🇫': 'Flags',
    '🇼🇸': 'Flags',
    '🇽🇰': 'Flags',
    '🇾🇪': 'Flags',
    '🇾🇹': 'Flags',
    '🇿🇦': 'Flags',
    '🇿🇲': 'Flags',
    '🇿🇼': 'Flags',
    '🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f': 'Flags',
    '🏴\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f': 'Flags',
    '🏴\U000e0067\U000e0062\U000e0077\U000e006c\U000e0073\U000e007f': 'Flags',
}
